name: plankton-app
region: tor
static_sites:
- environment_slug: html
  github:
    branch: mintek-main
    deploy_on_push: true
    repo: Website-Templates-1/professionals
  name: professionals-mintech-html
  output_dir: ../public
  routes:
  - path: /
  source_dir: mintech/html